myapp/urls.py
from django.urls import path
from .views import (
    LoginView,
    update_presence,
    GuideDetailView,
    SerrefilsListView,
    SerrefilsDetailView,
    maintenance_list,
    EtageListView,
    MonthlyAttendanceReportView,
    SerrefilsDetailView,
    GuideViewSet,
    SerrefilsViewSet,
    GuideListView,
    get_presence_status,

)
from .views import CreateAdminUserView
from . import views

urlpatterns = [
    path('login/', LoginView.as_view(), name='login'),
    path('update_presence/', update_presence, name='update_presence'),
    path('guides/', GuideListView.as_view(), name='guide-list-create'),
    path('guides/<int:pk>/', GuideDetailView.as_view(), name='guide-detail'),
    path('serrefils/', SerrefilsListView.as_view(), name='serrefils-list-create'),
    path('serrefils/<int:pk>/', SerrefilsDetailView.as_view(), name='serrefils-detail'),
    path('create-admin/', CreateAdminUserView.as_view(), name='create-admin'),
    path('maintenance/', maintenance_list, name='maintenance-list-create'),
    path('etages/', EtageListView.as_view(), name='etage-list'),
    path('presence-statistics/', views.presence_statistics, name='presence-statistics'),
    path('get_presence_status/<int:user_id>/', get_presence_status, name='get_presence_status'),
    path('monthly-attendance-report/', MonthlyAttendanceReportView.as_view(), name='monthly-attendance-report'),
    path('profile/<int:user_id>/', views.profile_details, name='profile-details'),

]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('employee/api/', include('myapp.urls')),
    path('webapp/', include('webapp.urls')),  
]

webapp/urls.py
from django.urls import path
from .views import CustomLoginView, user_info, AdminDashboardView, logout_view
from . import views

app_name = 'webapp'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('user-info/', user_info, name='user_info'),
    path('admin-dashboard/', AdminDashboardView.as_view(), name='admin_dashboard'),
    path('guides/', views.guide_list, name='guide_list'),
    path('serrefils/', views.serrefils_list, name='serrefils_list'),
    path('maintenance/', views.maintenance_list, name='maintenance_list'),
    path('logout/', logout_view, name='logout'),
]

myapp/models.py
# models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.db.models.signals import post_delete
from django.core.mail import send_mail
from django.utils import timezone
from .tasks import send_maintenance_notification
from datetime import timedelta  

class Etage(models.Model):
    number = models.IntegerField(unique=True)

    def __str__(self):
        return str(self.number)

class MyUserManager(BaseUserManager):
    def create_user(self, email, nom, prenom, contact, password=None, **extra_fields):
        if not email:
            raise ValueError('The Email field must be set')
        email = self.normalize_email(email)
        etage_number = extra_fields.pop('etage', None)
        etage = Etage.objects.get_or_create(number=etage_number)[0] if etage_number else None
        user = self.model(email=email, nom=nom, prenom=prenom, contact=contact, etage=etage, **extra_fields)
        if password:
            user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, nom, prenom, contact, password=None, **extra_fields):
        extra_fields.setdefault('is_admin', True)
        extra_fields.setdefault('is_employee', False)
        return self.create_user(email, nom, prenom, contact, password, **extra_fields)

class Utilisateur(AbstractBaseUser):
    id = models.AutoField(primary_key=True)
    nom = models.CharField(max_length=50)
    prenom = models.CharField(max_length=50)
    email = models.EmailField(unique=True)
    contact = models.CharField(max_length=20)
    is_admin = models.BooleanField(default=False)
    is_employee = models.BooleanField(default=False)
    role = models.CharField(max_length=10, choices=[
        ('', 'Select Role'),
        ('HSE', 'HSE'),
        ('Guide', 'Guide'),
        ('Serrefils', 'Serrefils'),
    ], blank=True, null=True, default='')
    etage = models.ForeignKey(Etage, on_delete=models.SET_NULL, null=True, blank=True)

    objects = MyUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['nom', 'prenom', 'contact']

    def __str__(self):
        return self.email

    def save(self, *args, **kwargs):
        if self.is_admin:
            self.is_employee = False
            self.role = ''
        elif self.role:
            self.is_employee = True
        super(Utilisateur, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Utilisateur"
        verbose_name_plural = "Utilisateurs"


@receiver(post_save, sender=Utilisateur)
def create_employe(sender, instance, created, **kwargs):
    if created:
        if instance.role in ['Guide', 'Serrefils', 'HSE']:
            employe, created = Employe.objects.get_or_create(utilisateur=instance)
            
            if instance.role == 'Guide':
                Guide.objects.get_or_create(utilisateur=instance, etage=instance.etage)
            elif instance.role == 'Serrefils':
                Serrefils.objects.get_or_create(utilisateur=instance, etage=instance.etage)
            elif instance.role == 'HSE':
                HSE.objects.get_or_create(utilisateur=instance, etage=instance.etage)


class Employe(models.Model):
    utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)

class Guide(models.Model):
    utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)
    etage = models.ForeignKey(Etage, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        verbose_name = "Guide"
        verbose_name_plural = "Guides"

class Serrefils(models.Model):
    utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)
    etage = models.ForeignKey(Etage, on_delete=models.SET_NULL, null=True, blank=True)
    class Meta:
        verbose_name = "Serrefils"
        verbose_name_plural = "Serrefils"

class Presence(models.Model):
    id_presence = models.AutoField(primary_key=True)
    utilisateur = models.ForeignKey(Utilisateur, on_delete=models.CASCADE)
    etage = models.ForeignKey(Etage, on_delete=models.CASCADE)
    date_heure = models.DateTimeField(auto_now_add=True)
    status = models.BooleanField()

    def __str__(self):
        return f"{self.utilisateur.email} - {self.etage.number} - {self.date_heure}"
    class Meta:
        verbose_name = "Presence"
        verbose_name_plural = "Presences"

class HSE(models.Model):
    utilisateur = models.OneToOneField(Utilisateur, on_delete=models.CASCADE)
    etage = models.ForeignKey(Etage, on_delete=models.SET_NULL, null=True, blank=True)
    
    class Meta:
        verbose_name = "HSE"
        verbose_name_plural = "HSE"

@receiver(post_delete, sender=Guide)
@receiver(post_delete, sender=Serrefils)
@receiver(post_delete, sender=HSE)
def delete_related_objects(sender, instance, **kwargs):
    Utilisateur.objects.filter(id=instance.utilisateur.id).delete()
    Employe.objects.filter(utilisateur_id=instance.utilisateur.id).delete()


from django.db import models
from django.utils import timezone
from datetime import timedelta

class Maintenance(models.Model):
    TYPE_CHOICES = [
        ('Extincteur', 'Extincteur'),
        ('Alarme', 'Alarme'),
    ]
    type = models.CharField(max_length=50, choices=TYPE_CHOICES)
    date_de_maintenance = models.DateField()
    etage = models.ForeignKey('Etage', on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.type} - {self.date_de_maintenance} - {self.etage}"

    def save(self, *args, **kwargs):
        is_new = self.pk is None
        super().save(*args, **kwargs)
        if is_new:
            self.schedule_notification()

    def schedule_notification(self):
        from myapp.tasks import send_maintenance_notification  
        notification_date = self.date_de_maintenance + timedelta(days=11*30)
        send_maintenance_notification.apply_async(
            args=[self.type, self.etage_id, self.date_de_maintenance], 
            eta=notification_date
        )

webapp/forms.py
# forms.py

from django import forms
from django.contrib.auth.forms import AuthenticationForm

class CustomLoginForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=254, widget=forms.EmailInput(attrs={'autocomplete': 'email'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'autocomplete': 'current-password'}))

webapp/views.py
from django.shortcuts import render
from django.db.models import Count, Q, Subquery, OuterRef
from django.utils import timezone
from datetime import timedelta
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import render
from django.db.models import Count, OuterRef, Subquery
from myapp.models import Etage, Presence
from myapp import models
from django.contrib.auth import authenticate, login as auth_login
from django.shortcuts import redirect, render
from django.views import View
from .forms import CustomLoginForm
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404
from django.contrib.auth.decorators import login_required
from .decorators import admin_required
from django.shortcuts import render
from django.utils import timezone
from datetime import timedelta
from myapp.models import Etage, Presence, Maintenance
from django.db.models import Count
from django.db.models.functions import TruncDate
from django.shortcuts import render
from myapp.models import Guide, Serrefils
from django.contrib.auth import logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.decorators import method_decorator


class CustomLoginView(View):
    form_class = CustomLoginForm
    template_name = 'employee_register/login.html'

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(request, email=email, password=password)
            if user is not None:
                auth_login(request, user)
                if user.is_admin:
                    return redirect('webapp:admin_dashboard')
            else:
                form.add_error(None, 'Invalid email or password')
        return render(request, self.template_name, {'form': form})

class AdminRequiredMixin:
    @method_decorator(admin_required)
    def dispatch(self, *args, **kwargs):
        return super().dispatch(*args, **kwargs)

def get_latest_presences():
    latest_presence_subquery = Presence.objects.filter(
        utilisateur_id=OuterRef('utilisateur_id')
    ).order_by('-date_heure').values('date_heure')[:1]

    latest_presences = Presence.objects.filter(
        date_heure=Subquery(latest_presence_subquery)
    ).select_related('utilisateur', 'etage').order_by('utilisateur__id')

    return latest_presences

class AdminDashboardView(LoginRequiredMixin, AdminRequiredMixin, View):
    def get(self, request):
        latest_presences = get_latest_presences()
        all_floors = Etage.objects.all()
        presence_stats = (latest_presences
                          .filter(status=True)
                          .values('etage__number')
                          .annotate(count=Count('utilisateur'))
                          .order_by('etage__number'))

        floor_presence_counts = {floor.number: 0 for floor in all_floors}
        for stat in presence_stats:
            floor_presence_counts[stat['etage__number']] = stat['count']
        today = timezone.now()
        thirty_days_ago = today - timedelta(days=30)
        floor_data = []
        for floor in all_floors:
            presence_count = Presence.objects.filter(
                etage=floor,
                date_heure__gte=thirty_days_ago,
                date_heure__lte=today,
                status=True
            ).annotate(date=TruncDate('date_heure')).values('date').distinct().count()
            presence_rate = (presence_count / 30) * 100
            floor_data.append({
                'floor_number': floor.number,
                'presence_count': presence_count,
                'presence_rate': round(presence_rate, 2)
            })
        context = {
            'floor_presence_counts': floor_presence_counts,
            'floor_data': floor_data
        }
        return render(request, 'employee_register/admin_dashboard.html', context)

@login_required
@admin_required
def user_info(request):
    if not isinstance(request.user, Utilisateur):
        # Handle the case where request.user is not Utilisateur instance
        # Redirect to login or handle error
        pass

    utilisateur = request.user

    context = {
        'utilisateur': utilisateur,
    }

    return render(request, 'employee_register/user_info.html', context)

@login_required
@admin_required
def guide_list(request):
    last_presence_subquery = Presence.objects.filter(
        utilisateur=OuterRef('utilisateur')
    ).order_by('-date_heure').values('status')[:1]

    guides = Guide.objects.select_related('utilisateur', 'etage').annotate(
        last_status=Subquery(last_presence_subquery)
    )
    
    return render(request, 'employee_register/guide_list.html', {'guides': guides})

@login_required
@admin_required
def serrefils_list(request):
    last_presence_subquery = Presence.objects.filter(
        utilisateur=OuterRef('utilisateur')
    ).order_by('-date_heure').values('status')[:1]

    serrefils = Serrefils.objects.select_related('utilisateur', 'etage').annotate(
        last_status=Subquery(last_presence_subquery)
    )

    return render(request, 'employee_register/serrefils_list.html', {'serrefils': serrefils})

@login_required
@admin_required
def maintenance_list(request):
    fire_maintenances = Maintenance.objects.filter(type='Extincteur')
    smoke_maintenances = Maintenance.objects.filter(type='Alarme')
    context = {
        'fire_maintenances': fire_maintenances,
        'smoke_maintenances': smoke_maintenances,
    }
    return render(request, 'employee_register/maintenance_list.html', context)

from django.contrib.auth import logout

def logout_view(request):
    logout(request)
    return redirect('webapp:login')

webapp/templates/employee_register/admin_dashboard.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Panel</title>
    <link rel="stylesheet" href="{% static 'style.css' %}" />
    <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>
  </head>
  <body>
    <div class="side-menu">
      <div class="brand-name">
        <h1>Admin</h1>
      </div>
      <ul>
        <li>
          <a href="http://127.0.0.1:8000/webapp/admin-dashboard/">
            <img src="{% static 'img/dashboard.png' %}" alt="" />&nbsp;Dashboard
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/guides/">
            <img src="{% static 'img/employees.png' %}" alt="" />&nbsp;Guides
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/serrefils/">
            <img
              src="{% static 'img/firefighter.png' %}"
              alt=""
            />&nbsp;Serre-files
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/maintenance/">
            <img src="{% static 'img/tools.png' %}" alt="" />&nbsp;Maintenance
          </a>
        </li>
      </ul>
    </div>

    <div class="container">
      <div class="header">
        <div class="nav">
          <div class="brand">
            <h1 style="color: #009999">SIEMENS</h1>
          </div>
          <div class="user">
            <div class="img-case" onclick="toggleDropdown()">
              <img src="{% static 'img/user.png' %}" alt="User Icon" />
            </div>
            <div id="userDropdown" class="user-dropdown">
              <a
                href="http://127.0.0.1:8000/webapp/logout/"
                class="logout-button"
                >Logout</a
              >
            </div>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="cards">
          {% for floor_number, count in floor_presence_counts.items %}
          <div class="card">
            <div class="box">
              <h2>{{ count }}</h2>
              <h3>Floor {{ floor_number }}</h3>
            </div>
            <div class="icon-case">
              <img src="{% static 'img/user.png' %}" alt="User Icon" />
            </div>
          </div>
          {% endfor %}
        </div>
        <div class="monthly-report">
          <div class="report-content">
            <div class="table-container">
              <table>
                <thead>
                  <tr>
                    <th>Étage</th>
                    <th>Nombre de présences</th>
                    <th>Taux de présence (%)</th>
                  </tr>
                </thead>
                <tbody>
                  {% for data in floor_data %}
                  <tr>
                    <td>Étage {{ data.floor_number }}</td>
                    <td>{{ data.presence_count }}</td>
                    <td>{{ data.presence_rate }}%</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
            <div class="chart-container">
              <canvas id="presenceChart"></canvas>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      function toggleDropdown() {
        document.getElementById("userDropdown").classList.toggle("show");
      }

      window.onclick = function(event) {
        if (!event.target.matches('.img-case img')) {
          var dropdowns = document.getElementsByClassName("user-dropdown");
          for (var i = 0; i < dropdowns.length; i++) {
            var openDropdown = dropdowns[i];
            if (openDropdown.classList.contains('show')) {
              openDropdown.classList.remove('show');
            }
          }
        }
      };

      document.addEventListener("DOMContentLoaded", function () {
          const floorData = {{ floor_data|safe }};
          const labels = floorData.map(data => `Étage ${data.floor_number}`);
          const presenceRates = floorData.map(data => data.presence_rate);

          const ctx = document.getElementById('presenceChart').getContext('2d');
          new Chart(ctx, {
              type: 'pie',
              data: {
                  labels: labels,
                  datasets: [{
                      label: 'Taux de présence (%)',
                      data: presenceRates,
                      backgroundColor: [
                          '#FF6384',
                          '#36A2EB',
                          '#FFCE56',
                          '#4BC0C0',
                          '#9966FF'
                      ],
                      hoverOffset: 4
                  }]
              },
              options: {
                  responsive: true,
                  plugins: {
                      legend: {
                          position: 'top',
                      },
                      tooltip: {
                          callbacks: {
                              label: function (context) {
                                  const label = context.label || '';
                                  const value = context.raw || 0;
                                  return `${label}: ${value}%`;
                              }
                          }
                      }
                  }
              }
          });
      });
    </script>
  </body>
</html>

webapp/templates/employee_register/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Admin Dashboard</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styling.css' %}" />
  </head>
  <body>
    {% block content %} 
    {% endblock content %}
  </body>
</html>

webapp/templates/employee_register/guide_list.html
<!-- guide_list.html -->
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Liste des Guides</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styling.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
  </head>
  <body>
    <div class="side-menu">
      <div class="brand-name">
        <h1>Admin</h1>
      </div>
      <ul>
        <li>
          <a href="http://127.0.0.1:8000/webapp/admin-dashboard/">
            <img src="{% static 'img/dashboard.png' %}" alt="" />&nbsp;Dashboard
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/guides/">
            <img src="{% static 'img/employees.png' %}" alt="" />&nbsp;Guides
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/serrefils/">
            <img
              src="{% static 'img/firefighter.png' %}"
              alt=""
            />&nbsp;Serre-files
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/maintenance/">
            <img src="{% static 'img/tools.png' %}" alt="" />&nbsp;Maintenance
          </a>
        </li>
      </ul>
    </div>

    <div class="container">
      <div class="header">
        <div class="nav">
          <div class="brand">
            <h1 style="color: #009999">SIEMENS</h1>
          </div>
        </div>
      </div>

      <div class="content">
        <div class="title">
          <h1>Liste des Guides</h1>
        </div>

        <div class="table-container">
          <table>
            <thead>
              <tr class="heading">
                <th>ID</th>
                <th>Nom</th>
                <th>Prénom</th>
                <th>Email</th>
                <th>Role</th>
                <th>Etage</th>
                <th>Status</th>
              </tr>
            </thead>

            <tbody class="userInfo">
              {% for guide in guides %}
              <tr>
                <td>{{ guide.utilisateur.id }}</td>
                <td>{{ guide.utilisateur.nom }}</td>
                <td>{{ guide.utilisateur.prenom }}</td>
                <td>{{ guide.utilisateur.email }}</td>
                <td>{{ guide.utilisateur.role }}</td>
                <td>{{ guide.utilisateur.etage.number }}</td>
                <td>
                  {% if guide.last_status %}
                  <span class="status-circle present"></span>
                  {% else %}
                  <span class="status-circle absent"></span>
                  {% endif %}
                </td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </body>
</html>

webapp/templates/employee_register/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    {% load static %}
    <link rel="stylesheet" href="{% static 'loginStyle.css' %}" />
    <title>LogIn</title>
</head>
<body>
    <div class="login-page">
        <div class="form-container">
            <div class="logo">
                <h1>SIEMENS</h1>
            </div>
            <div class="form">
                <form class="login-form" method="post">
                    {% csrf_token %}
                    <input type="email" name="email" placeholder="Email" required />
                    <input type="password" name="password" placeholder="Password" required />
                    <button type="submit">Login</button>
                </form>
            </div>
        </div>
    </div>
</body>
</html>

webapp/templates/employee_register/maintenance_list.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Liste des Maintenances</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'styling.css' %}" />
    <link
      rel="stylesheet"
      href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css"
    />
  </head>
  <body>
    <div class="side-menu">
      <div class="brand-name">
        <h1>Admin</h1>
      </div>
      <ul>
        <li>
          <a href="http://127.0.0.1:8000/webapp/admin-dashboard/">
            <img src="{% static 'img/dashboard.png' %}" alt="" />&nbsp;Dashboard
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/guides/">
            <img src="{% static 'img/employees.png' %}" alt="" />&nbsp;Guides
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/serrefils/">
            <img
              src="{% static 'img/firefighter.png' %}"
              alt=""
            />&nbsp;Serre-files
          </a>
        </li>
        <li>
          <a href="http://127.0.0.1:8000/webapp/maintenance/">
            <img src="{% static 'img/tools.png' %}" alt="" />&nbsp;Maintenance
          </a>
        </li>
      </ul>
    </div>

    <div class="container">
      <div class="header">
        <div class="nav">
          <div class="brand">
            <h1 style="color: #009999">SIEMENS</h1>
          </div>
        </div>
      </div>
      <div class="content">
        <div class="button-container">
          <img
            id="fireButton"
            class="icon-button"
            src="{% static 'img/fire.png' %}"
            alt="Fire"
          />
          <img
            id="smokeButton"
            class="icon-button"
            src="{% static 'img/smoke.png' %}"
            alt="Smoke"
          />
        </div>

        <!-- Modal for Fire Table -->
        <div id="fireModal" class="modal">
          <div class="modal-content">
            <span class="close-btn" onclick="closeModal('fireModal')"
              >&times;</span
            >
            <h2>Extincteur Maintenance</h2>
            <div class="table-container">
              <table>
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Date de Maintenance</th>
                    <th>Etage</th>
                  </tr>
                </thead>
                <tbody>
                  {% for maintenance in fire_maintenances %}
                  <tr>
                    <td>{{ maintenance.id }}</td>
                    <td>{{ maintenance.get_type_display }}</td>
                    <td>{{ maintenance.date_de_maintenance }}</td>
                    <td>{{ maintenance.etage }}</td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="4">No maintenance records found.</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- Modal for Smoke Table -->
        <div id="smokeModal" class="modal">
          <div class="modal-content">
            <span class="close-btn" onclick="closeModal('smokeModal')"
              >&times;</span
            >
            <h2>Alarme Maintenance</h2>
            <div class="table-container">
              <table>
                <thead>
                  <tr>
                    <th>ID</th>
                    <th>Type</th>
                    <th>Date de Maintenance</th>
                    <th>Etage</th>
                  </tr>
                </thead>
                <tbody>
                  {% for maintenance in smoke_maintenances %}
                  <tr>
                    <td>{{ maintenance.id }}</td>
                    <td>{{ maintenance.get_type_display }}</td>
                    <td>{{ maintenance.date_de_maintenance }}</td>
                    <td>{{ maintenance.etage }}</td>
                  </tr>
                  {% empty %}
                  <tr>
                    <td colspan="4">No maintenance records found.</td>
                  </tr>
                  {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        <!-- Logout Modal -->
        <div id="logoutModal" class="modal">
          <div class="modal-content">
            <span class="close-btn" onclick="closeModal('logoutModal')"
              >&times;</span
            >
            <h2>Logout Confirmation</h2>
            <p>Are you sure you want to logout?</p>
            <div class="button-container">
              <button onclick="logout()">Logout</button>
              <button onclick="closeModal('logoutModal')">Cancel</button>
            </div>
          </div>
        </div>
      </div>
    </div>

    <script>
      document.getElementById("fireButton").onclick = function () {
        document.getElementById("fireModal").style.display = "block";
      };
      document.getElementById("smokeButton").onclick = function () {
        document.getElementById("smokeModal").style.display = "block";
      };

      function showLogoutPopup() {
        document.getElementById("logoutModal").style.display = "block";
      }

      function closeModal(modalId) {
        document.getElementById(modalId).style.display = "none";
      }

      function logout() {
        window.location.href = "http://127.0.0.1:8000/logout";
      }

      // Close the modal when clicking outside of it
      window.onclick = function (event) {
        if (event.target.classList.contains("modal")) {
          event.target.style.display = "none";
        }
      };
    </script>
  </body>
</html>

webapp/templates/employee_register/utilisateur_form.html
{% extends 'employee_register/base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="dark_bg open"></div>
<div class="popup open">
    <header>
        <h2>New Employee</h2>
    </header>
    <form action="" method="post" autocomplete="off">
        {% csrf_token %}
        {{ form|crispy }}
        <footer>
            <button type="submit" class="submitBtn">
                <i class="fas fa-database"></i> Submit
            </button>
            <a href="{% url 'utilisateur_list' %}" class="backBtn">
                <i class="fas fa-stream"></i> Back to list
            </a>
        </footer>
    </form>
</div>
<script>
function closeForm() {
    document.querySelector('.popup').classList.remove('open');
    document.querySelector('.dark_bg').style.opacity = '0';
    document.querySelector('.dark_bg').style.visibility = 'hidden';
}
</script>
{% endblock %}